server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/thehome
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        max_fetch_depth: 3
    show-sql: true
    generate-ddl: true

thehome:
  api:
    user: admin
    password: admin

springdoc:
  swagger-ui:
    operations-sorter: method
