#arquivo de configuracoes local/default

#port config
server:
  port: ${SERVER_PORT}

#profile config
spring:
  application:
    name: "thehome-api"

  config:
    activate:
      on-profile:
        - dev

  #database config
  datasource:
    url: jdbc:postgresql://postgres-db:5432/thehome?currentSchema=public
    username: "postgres"
    password: "root"
    driver-class-name: "org.postgresql.Driver"

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

thehome:
  api:
    user: admin
    password: admin

springdoc:
  swagger-ui:
    operations-sorter: method
